### ISSUE TITLE
Employer Branch ID Incorrectly Showing as 0 When Retrieved from Database

### ISSUE THREAD

**Issue by TheTharz** [Life-Pill/pharmacy-pos-backend#86] opened 2024-05-08 08:32 UTC
### Issue Title:
Employer Branch ID Incorrectly Showing as 0 When Retrieved from Database

#### Problem:
When retrieving employer data from the database, the branch ID for each employer is incorrectly showing as 0, even though the branch is correctly assigned to each employer in the system.

#### Expected Behavior:
The branch ID associated with each employer should reflect the actual branch they are assigned to. This information is crucial for proper management and categorization of employers based on their branches.

#### Steps to Reproduce:
1. Retrieve employer data from the database using the appropriate query or API endpoint.
2. Examine the retrieved data for the branch ID field (`branchId`).
3. Notice that the `branchId` for all employers is showing as 0 instead of the actual branch ID they are assigned to.

#### Impact:
- This issue affects the accuracy and reliability of employer data in the system.
- It may cause confusion and incorrect categorization of employers based on their branches.

**Comment by PramithaMJ** [comment] 2024-05-09 08:32
This issue seems to stem from a discrepancy between the data stored in the database and the expected behavior when retrieving employer information.
 The fact that all retrieved branch IDs are showing as 0 indicates a potential problem with how branch IDs are being stored or retrieved.

To investigate further, we should examine the code or query responsible for retrieving employer data and inspect the database schema to ensure that branch IDs are being properly associated with each employer.
 Additionally, we should verify that the branch IDs are correctly assigned and updated when new employers are added or when existing employers are assigned to different branches.

Once the root cause of the issue is identified, we can implement the necessary fixes to ensure that the branch IDs are accurately reflected in the retrieved employer data. This will help maintain the integrity of the system and ensure that employers are correctly categorized based on their branches.

`could you please specify which endpoint or API is being used to retrieve employer data? Understanding the endpoint involved will help us pinpoint where in the system the branch IDs are being incorrectly represented as zero. With this information, we can proceed with a targeted investigation to resolve the issue effectively.`

**Comment by TheTharz** [comment] 2024-05-09 09:13
## Issue Summary
The discrepancy observed in the retrieved branch IDs showing as 0 appears to be linked to the `login` endpoint functionality.

`http://localhost:8080/lifepill/v1/auth/authenticate`

**Closed** 2024-05-09 11:56 UTC
Labels: bug
